ECommerce.Front.Admin/Pages/BlogAuthors/Create.cshtml.cs
using Ecommerce.Entities;
using Ecommerce.Entities.Helper;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogAuthors;

public class CreateModel : PageModel
{
    private readonly IBlogAuthorService _blogAuthorService;
    private readonly IHostEnvironment _environment;
    private readonly IImageService _imageService;

    public CreateModel(IBlogAuthorService blogAuthorService, IImageService imageService, IHostEnvironment environment)
    {
        _blogAuthorService = blogAuthorService;
        _imageService = imageService;
        _environment = environment;
    }

    [BindProperty] public BlogAuthor BlogAuthor { get; set; }

    [BindProperty] public IFormFile Upload { get; set; }

    [TempData] public string Message { get; set; }

    [TempData] public string Code { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        if (Upload == null)
        {
            Message = "لطفا عکس را انتخاب کنید";
            Code = ServiceCode.Error.ToString();
            return Page();
        }

        var fileName = (await _imageService.Upload(Upload, "Images/BlogAuthors", _environment.ContentRootPath))
            .ReturnData;
        BlogAuthor.ImagePath = $"/{fileName[0]}/{fileName[1]}/{fileName[2]}";

        if (ModelState.IsValid)
        {
            var result = await _blogAuthorService.Add(BlogAuthor);
            if (result.Code == 0)
                return RedirectToPage("/BlogAuthors/Index",
                    new {message = result.Message, code = result.Code.ToString()});
            Message = result.Message;
            Code = result.Code.ToString();
            ModelState.AddModelError("", result.Message);
        }

        return Page();
    }
}

ECommerce.Front.Admin/Pages/BlogAuthors/Delete.cshtml.cs
using Ecommerce.Entities;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogAuthors;

public class DeleteModel : PageModel
{
    private readonly IBlogAuthorService _blogAuthorService;

    public DeleteModel(IBlogAuthorService blogAuthorService)
    {
        _blogAuthorService = blogAuthorService;
    }

    public BlogAuthor BlogAuthor { get; set; }
    [TempData] public string Message { get; set; }

    [TempData] public string Code { get; set; }

    public async Task<IActionResult> OnGet(int id)
    {
        var result = await _blogAuthorService.GetById(id);
        if (result.Code == 0)
        {
            BlogAuthor = result.ReturnData;
            return Page();
        }

        return RedirectToPage("/BlogAuthors/Index",
            new {message = result.Message, code = result.Code.ToString()});
    }

    public async Task<IActionResult> OnPost(int id)
    {
        if (ModelState.IsValid)
        {
            var result = await _blogAuthorService.Delete(id);
            Message = result.Message;
            Code = result.Code.ToString();
            if (result.Code == 0)
                return RedirectToPage("/BlogAuthors/Index",
                    new {message = result.Message, code = result.Code.ToString()});
            Message = result.Message;
            Code = result.Code.ToString();
        }

        return Page();
    }
}

ECommerce.Front.Admin/Pages/BlogAuthors/Detail.cshtml.cs
using Ecommerce.Entities;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogAuthors;

public class DetailModel : PageModel
{
    private readonly IBlogAuthorService _blogAuthorService;

    public DetailModel(IBlogAuthorService blogAuthorService)
    {
        _blogAuthorService = blogAuthorService;
    }

    public BlogAuthor BlogAuthor { get; set; }

    public async Task<IActionResult> OnGet(int id)
    {
        var result = await _blogAuthorService.GetById(id);
        if (result.Code == 0)
        {
            BlogAuthor = result.ReturnData;
            return Page();
        }

        return RedirectToPage("/BlogAuthors/Index",
            new {message = result.Message, code = result.Code.ToString()});
    }
}

ECommerce.Front.Admin/Pages/BlogAuthors/Edit.cshtml.cs
using Ecommerce.Entities;
using Ecommerce.Entities.Helper;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogAuthors;

public class EditModel : PageModel
{
    private readonly IBlogAuthorService _blogAuthorService;
    private readonly IHostEnvironment _environment;
    private readonly IImageService _imageService;

    public EditModel(IBlogAuthorService blogAuthorService, IHostEnvironment environment, IImageService imageService)
    {
        _blogAuthorService = blogAuthorService;
        _environment = environment;
        _imageService = imageService;
    }

    [BindProperty] public IFormFile? Upload { get; set; }
    [BindProperty] public BlogAuthor BlogAuthor { get; set; }
    [TempData] public string Message { get; set; }
    [TempData] public string Code { get; set; }

    public async Task OnGet(int id)
    {
        var result = await _blogAuthorService.GetById(id);
        BlogAuthor = result.ReturnData;
    }

    public async Task<IActionResult> OnPost()
    {
        if (Upload != null)
        {
            var fileName = (await _imageService.Upload(Upload, "Images/BlogAuthors", _environment.ContentRootPath))
                .ReturnData;
            BlogAuthor.ImagePath = $"/{fileName[0]}/{fileName[1]}/{fileName[2]}";
        }

        if (Upload == null && BlogAuthor.ImagePath == null)
        {
            Message = "لطفا عکس را انتخاب کنید";
            Code = ServiceCode.Error.ToString();
            return Page();
        }

        if (ModelState.IsValid)
        {
            var result = await _blogAuthorService.Edit(BlogAuthor);
            Message = result.Message;
            Code = result.Code.ToString();
            if (result.Code == 0)
                return RedirectToPage("/BlogAuthors/Index",
                    new {message = result.Message, code = result.Code.ToString()});
            Message = result.Message;
            Code = result.Code.ToString();
            ModelState.AddModelError("", result.Message);
        }

        return Page();
    }
}

ECommerce.Front.Admin/Pages/BlogCategories/Create.cshtml.cs
using Ecommerce.Entities;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogCategories;

public class CreateModel : PageModel
{
    private readonly IBlogCategoryService _blogCategoryService;

    public CreateModel(IBlogCategoryService blogCategoryService)
    {
        _blogCategoryService = blogCategoryService;
    }

    [BindProperty] public BlogCategory BlogCategory { get; set; }

    [TempData] public string Message { get; set; }

    [TempData] public string Code { get; set; }

    public void OnGet()
    {
    }

    public async Task<IActionResult> OnPost()
    {
        if (ModelState.IsValid)
        {
            var result = await _blogCategoryService.Add(BlogCategory);
            if (result.Code == 0)
                return RedirectToPage("/BlogCategories/Index",
                    new {message = result.Message, code = result.Code.ToString()});
            Message = result.Message;
            Code = result.Code.ToString();
            ModelState.AddModelError("", result.Message);
        }

        return Page();
    }
}

ECommerce.Front.Admin/Pages/BlogCategories/Delete.cshtml.cs
using Ecommerce.Entities;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogCategories;

public class DeleteModel : PageModel
{
    private readonly IBlogCategoryService _blogcategoryService;

    public DeleteModel(IBlogCategoryService blogcategoryService)
    {
        _blogcategoryService = blogcategoryService;
    }

    public BlogCategory BlogCategory { get; set; }
    [TempData] public string Message { get; set; }

    [TempData] public string Code { get; set; }

    public async Task<IActionResult> OnGet(int id)
    {
        var result = await _blogcategoryService.GetById(id);
        if (result.Code == 0)
        {
            BlogCategory = result.ReturnData;
            return Page();
        }

        return RedirectToPage("/BlogCategories/Index",
            new {message = result.Message, code = result.Code.ToString()});
    }

    public async Task<IActionResult> OnPost(int id)
    {
        if (ModelState.IsValid)
        {
            var result = await _blogcategoryService.Delete(id);
            Message = result.Message;
            Code = result.Code.ToString();
            if (result.Code == 0)
                return RedirectToPage("/BlogCategories/Index",
                    new {message = result.Message, code = result.Code.ToString()});
            Message = result.Message;
            Code = result.Code.ToString();
        }

        return Page();
    }
}

ECommerce.Front.Admin/Pages/BlogCategories/Detail.cshtml.cs
using Ecommerce.Entities;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogCategories;

public class DetailModel : PageModel
{
    private readonly IBlogCategoryService _blogcategoryService;

    public DetailModel(IBlogCategoryService blogcategoryService)
    {
        _blogcategoryService = blogcategoryService;
    }

    public BlogCategory BlogCategory { get; set; }

    public async Task<IActionResult> OnGet(int id)
    {
        var result = await _blogcategoryService.GetById(id);
        if (result.Code == 0)
        {
            BlogCategory = result.ReturnData;
            return Page();
        }

        return RedirectToPage("/BlogCategories/Index",
            new {message = result.Message, code = result.Code.ToString()});
    }
}

ECommerce.Front.Admin/Pages/BlogCategories/Edit.cshtml.cs
using Ecommerce.Entities;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.BlogCategories;

public class EditModel : PageModel
{
    private readonly IBlogCategoryService _blogcategoryService;

    public EditModel(IBlogCategoryService blogcategoryService)
    {
        _blogcategoryService = blogcategoryService;
    }

    [BindProperty] public BlogCategory BlogCategory { get; set; }
    [TempData] public string Message { get; set; }
    [TempData] public string Code { get; set; }

    public async Task OnGet(int id)
    {
        var result = await _blogcategoryService.GetById(id);
        BlogCategory = result.ReturnData;
    }

    public async Task<IActionResult> OnPost()
    {
        if (ModelState.IsValid)
        {
            var result = await _blogcategoryService.Edit(BlogCategory);
            Message = result.Message;
            Code = result.Code.ToString();
            if (result.Code == 0)
                return RedirectToPage("/BlogCategories/Index",
                    new {message = result.Message, code = result.Code.ToString()});
            Message = result.Message;
            Code = result.Code.ToString();
            ModelState.AddModelError("", result.Message);
        }

        return Page();
    }
}

ECommerce.Front.Admin/Pages/Blogs/Detail.cshtml.cs
using Ecommerce.Entities;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.Blogs;

public class DetailModel : PageModel
{
    private readonly IBlogService _blogService;

    public DetailModel(IBlogService blogService)
    {
        _blogService = blogService;
    }

    public Blog Blog { get; set; }

    public async Task<IActionResult> OnGet(int id)
    {
        var result = await _blogService.GetById(id);
        if (result.Code == 0)
        {
            Blog = result.ReturnData;
            return Page();
        }

        return RedirectToPage("/Blogs/Index",
            new {message = result.Message, code = result.Code.ToString()});
    }
}

ECommerce.Front.Admin/Pages/Blogs/Edit.cshtml.cs
using Ecommerce.Entities;
using Ecommerce.Entities.Helper;
using Ecommerce.Entities.ViewModel;
using ECommerce.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerce.Front.Admin.Pages.Blogs;

public class EditModel : PageModel
{
    private readonly IBlogService _blogService;
    private readonly IHostEnvironment _environment;
    private readonly IImageService _imageService;
    private readonly ITagService _tagService;
    private readonly IKeywordService _keywordService;
    private readonly IBlogAuthorService _blogAuthorService;
    private readonly IBlogCategoryService _blogCategoryService;

    public EditModel(IBlogService blogService, IImageService imageService, ITagService tagService,
        IKeywordService keywordService, IHostEnvironment environment, IBlogAuthorService blogAuthorService, IBlogCategoryService blogCategoryService)
    {
        _blogService = blogService;
        _environment = environment;
        _imageService = imageService;
        _keywordService = keywordService;
        _tagService = tagService;
        _blogAuthorService = blogAuthorService;
        _blogCategoryService = blogCategoryService;
    }

    [BindProperty] public BlogViewModel Blog { get; set; }
    [BindProperty] public IFormFile? Upload { get; set; }
    [TempData] public string Message { get; set; }
    [TempData] public string Code { get; set; }
    public List<Tag> Tags { get; set; }
    public List<Keyword> Keywords { get; set; }
    public List<BlogAuthor> BlogAuthors { get; set; }
    public List<BlogCategory> Categories { get; set; }


    public async Task<IActionResult> OnGet(int id)
    {
        //var result = await _blogService.GetById(id);
        //Blog = result.ReturnData;        
        
        var result = await Initial(id);
        if (result.Code == 0) return Page();
        return RedirectToPage("/Blogs/Index",
            new {message = result.Message, code = result.Code.ToString() });
    }

    public async Task<IActionResult> OnPost()
    {
        var _image = await _imageService.GetImagesByBlogId(Blog.Id);
        Blog.Image = _image.ReturnData;

        if (Upload != null && Blog.Image.Id!=0)
        {
            await _imageService.Delete($"Images/Blogs/{Blog.Image?.Name}", Blog.Image.Id, _environment.ContentRootPath);
            _image = await _imageService.GetImagesByBlogId(Blog.Id);
            Blog.Image = _image.ReturnData;
        }
        if (Upload != null && Blog.Image.Id == 0)
        {
            var resultImage = await _imageService.Add(Upload, Blog.Id, "Images/Blogs",
                       _environment.ContentRootPath);
            if (resultImage.Code > 0)
            {
                Message = resultImage.Message;
                Code = resultImage.Code.ToString();
                ModelState.AddModelError("", resultImage.Message);               
            }

            _image = await _imageService.GetImagesByBlogId(Blog.Id);
            Blog.Image = _image.ReturnData;
        }
        if (Upload == null && Blog.Image.Id == 0)
        {
            Message = "لطفا عکس را انتخاب کنید";
            Code = ServiceCode.Error.ToString();
            await Initial(Blog.Id);
            return Page();
        }

        if (ModelState.IsValid)
        {
            var result = await _blogService.Edit(Blog);
            if (result.Code == 0)
            {                  
                 
                return RedirectToPage("/Blogs/Index",
                    new {message = result.Message, code = result.Code.ToString() });
            }

            Message = result.Message;
            Code = result.Code.ToString();
            ModelState.AddModelError("", result.Message);
        }

        await Initial(Blog.Id);
        return Page();
    }

    private async Task<ServiceResult<BlogViewModel>> Initial(int id)
    {
        var result = await _blogService.GetById(id);
        if (result.Code > 0)
            return new ServiceResult<BlogViewModel>
            {
                Code = result.Code,
                Message = result.Message
            };
        Blog = result.ReturnData;

        Tags = (await _tagService.GetAll()).ReturnData;
        Keywords = (await _keywordService.GetAll()).ReturnData;
        Categories = (await _blogCategoryService.GetAll()).ReturnData;
        BlogAuthors = (await _blogAuthorService.GetAll()).ReturnData;
        //BlogAuthors = new SelectList(blogAuthors, nameof(BlogAuthor.Id), nameof(BlogAuthor.Name));


        return result;
    }

    public async Task<IActionResult> OnPostDeleteImage(string imageName, int id, int blogId)
    {        
            var result = await _imageService.Delete($"Images/Blogs/{imageName}", id, _environment.ContentRootPath);

            if (result.Code == 0)
                //return RedirectToPage("/Blogs/Edit",
                //    new { area = "Admin", message = result.Message, code = result.Code.ToString() });
            Message = result.Message;
            Code = result.Code.ToString();
            ModelState.AddModelError("", result.Message);
        
        await Initial(blogId);
        return Page();
    }
}

ECommerce.Front.Admin/Pages/Products/Edit.cshtml
@page
@model ECommerce.Front.Admin.Pages.Products.EditModel
@{
}
@if (Model.Message != null)
{
    switch (Model.Code)
    {
        case "Error":
            <div class="alert alert-danger"> @Model.Message </div>
            break;
        case "Warning":
            <div class="alert alert-warning"> @Model.Message </div>
            break;
        case "Info":
            <div class="alert alert-info"> @Model.Message </div>
            break;
        default:
            <div class="alert alert-success"> @Model.Message </div>
            break;
    }

    Model.Message = null;
}
<div class="container">
<div class="row">
<div class="col-lg-12 col-xxl-12 order-1 order-xxl-2 ">
<div class="card card-custom">
<div class="card-header">
    <h3 class="card-title">
        ویرایش محصولات
    </h3>
</div>
<!--begin::Form-->
<form class="form" method="post" asp-page-handler="OnPost" enctype="multipart/form-data">
    <input hidden="hidden" asp-for="@Model.Product.Id"/>
    <div class="card-body">
        @*  <div class="form-group">
                            <button type="button" class="btn btn-outline-success">انتخاب کالا از هلو</button>
                            <button type="button" class="btn btn-outline-success">افزودن اتوماتیک</button>
                        </div>*@
        <div class="form-group">
            <label>انتخاب تگ ها</label>
            <select asp-for="@Model.Product.TagsId" class="col-md-12 js-example-basic-multiple  form-control" multiple="multiple">
                @foreach (var item in Model.Tags)
                {
                    if (Model.Product.Tags.Any(x => x.Id == item.Id))
                    {
                        <option selected="selected" value="@item.Id">@item.TagText</option>
                    }
                    else
                    {
                        <option value="@item.Id">@item.TagText</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label>انتخاب کلمات کلیدی</label>
            <select asp-for="@Model.Product.KeywordsId" class="col-md-12 js-example-basic-multiple  form-control" multiple="multiple">
                @foreach (var item in Model.Keywords)
                {
                    if (Model.Product.Keywords.Any(x => x.Id == item.Id))
                    {
                        <option selected="selected" value="@item.Id">@item.KeywordText</option>
                    }
                    else
                    {
                        <option value="@item.Id">@item.KeywordText</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label>انتخاب دسته ها</label>
            <div class="checkbox-list">
                <partial name="_categoriesTree" model="Model.CategoryParentViewModel"/>
            </div>
        </div>
        <div class="form-group">
            <label>نام کالا</label>
            <input asp-for="@Model.Product.Name" class="form-control form-control-solid"/>
            <span asp-validation-for="@Model.Product.Name" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
            <label>توضیحات</label>
            <textarea id="Description_Add" asp-for="@Model.Product.Description" class="form-control form-control-solid"></textarea>
            <span asp-validation-for="@Model.Product.Description" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
	        <label>نقد و بررسی</label>
	        <textarea id="Review_Edit" asp-for="@Model.Product.Review" class="form-control form-control-solid"></textarea>
	        <span asp-validation-for="@Model.Product.Review" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
            <label>حداقل سفارش</label>
            <input asp-for="@Model.Product.MinOrder" id="kt_touchspin_4" class="form-control form-control-solid bootstrap-touchspin-vertical-btn"/>
            <span asp-validation-for="@Model.Product.MinOrder" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
            <label>حداکثر سفارش</label>
            <input asp-for="@Model.Product.MaxOrder" id="kt_touchspin_4" class="form-control form-control-solid bootstrap-touchspin-vertical-btn"/>
            <span asp-validation-for="@Model.Product.MaxOrder" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
            <label>حداقل در انبار</label>
            <input asp-for="@Model.Product.MinInStore" id="kt_touchspin_4" class="form-control form-control-solid bootstrap-touchspin-vertical-btn"/>
            <span asp-validation-for="@Model.Product.MinInStore" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
            <label>تعداد سفارش مجدد</label>
            <input asp-for="@Model.Product.ReorderingLevel" id="kt_touchspin_4" class="form-control form-control-solid bootstrap-touchspin-vertical-btn"/>
            <span asp-validation-for="@Model.Product.ReorderingLevel" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
            <label class="checkbox">
                <input type="checkbox" asp-for="@Model.Product.IsDiscontinued"/>
                <span></span>
                توقف تولید
            </label>
        </div>
        <div class="form-group">
            <label class="checkbox">
                <input type="checkbox" asp-for="@Model.Product.IsActive"/>
                <span></span>
                فعال بودن
            </label>
        </div>
        <div class="form-group">
            <label>آدرس محصول در سایت</label>
            <input asp-for="@Model.Product.Url" class="form-control form-control-solid"/>
            <span asp-validation-for="@Model.Product.Url" class="mt-5" style="color: red; margin-top: 10px"></span>
        </div>
        <div class="form-group">
            <label>برند</label>
            <select asp-for="@Model.Product.BrandId" class="col-md-12 js-example-basic-single form-control">
                @foreach (var item in Model.Brands)
                {
                    if (Model.Product.BrandId == item.Id)
                    {
                        <option selected="selected" value="@item.Id">@item.Name</option>
                    }
                    else
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label>انبار</label>
            <select asp-for="@Model.Product.StoreId" class="col-md-12 js-example-basic-single form-control">
                @foreach (var item in Model.Stores)
                {
                    if (Model.Product.StoreId == item.Id)
                    {
                        <option selected="selected" value="@item.Id">@item.Name</option>
                    }
                    else
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label>تامین کننده</label>
            <select asp-for="@Model.Product.SupplierId" class="col-md-12 js-example-basic-single form-control">
                @foreach (var item in Model.Suppliers)
                {
                    if (Model.Product.SupplierId == item.Id)
                    {
                        <option selected="selected" value="@item.Id">@item.Name</option>
                    }
                    else
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label>تصویر کالا</label>
            <div class="custom-file">
                <input asp-for="@Model.Uploads" type="file" class="custom-file-input" id="files" accept=".gif,.jpg,.jpeg,.png" multiple="multiple"/>
                <label class="custom-file-label" for="customفایل">انتخاب فایل</label>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-primary mr-2">ویرایش</button>
        <a class="btn btn-secondary" asp-Page="/Products/index">لغو</a>
    </div>
</form>
<div class="form-group">
    <label>تصویر کالا</label>
    <ul class="details-preview">

        @foreach (var image in Model.Product.Images)
        {
            <form class="form" method="post" asp-page-handler="DeleteImage">
                <li>
                    <img style="width: 50%" src="~/@($"{image.Path}/{image.Name}")" alt="@image.Alt">
                    <input name="imageName" value="@image.Name" hidden="hidden"/>
                    <input name="productId" value="@Model.Product.Id" hidden="hidden"/>
                    <input name="id" value="@image.Id" hidden="hidden"/>
                    <button type="submit">حذف</button>
                </li>
            </form>
        }
    </ul>
</div>
<!--end::Form-->
</div>
</div>
</div>
</div>

@section Scripts
{
    <script src="~/Admin/js/select2.min.js"></script>
    <script src="~/Admin/js/bootstrap-touchspin.js"></script>
    @*<script src="~/Admin/js/dropzonejs.js"></script>*@
<script src="~/Admin/js/ckeditor/ckeditor.js"></script>

    <script type="text/javascript">
        window.onload = function() {
            CKEDITOR.replace('Description_Add');
            CKEDITOR.replace('Review_Edit');
        };
        $(document).ready(function() {
            $('.js-example-basic-multiple').select2();
        });

    </script>
}

ECommerce.Front.Admin/Pages/Products/_categoriesTree.cshtml
@model List<Ecommerce.Entities.ViewModel.CategoryParentViewModel>
<div>
    @if (Model != null)
    {
        @foreach (var category in Model)
        {
            @if (category.Depth > 0)
            {
                for (var i = 0; i <= category.Depth; i++)
                {
                    <text> &nbsp; &nbsp; </text>
                }
            }
            <input
                @if (category.Checked)
                {
                    <text>checked="checked"</text>
                }
                type="checkbox" name="Product.CategoriesId" id="cat-@category.Id" value="@category.Id"
                @if (category.Children != null && category.Children.Count > 0)
                {
                    <text> disabled="disabled" </text>
                }>
            <label for="cat-@category.Id"> @category.Name</label>

            if (category.Children != null)
            {
                <partial name="_categoriesTree" model="category.Children"/>
            }
        }
    }
</div>